# Generated by Django 5.0.2 on 2024-04-11 03:20

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[main.models.validate_year]),
        ),
    ]
