# Generated by Django 5.0.2 on 2024-04-11 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_course_id_alter_course_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_id',
            new_name='id',
        ),
    ]
