# Generated by Django 5.0.2 on 2024-04-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_course_id_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_number',
            field=models.CharField(default='Default Course Number', max_length=10),
            preserve_default=False,
        ),
    ]
