# Generated by Django 5.0.2 on 2024-04-12 23:20

import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_course_course_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[main.models.validate_year]),
        ),
    ]
