# Generated by Django 5.0.2 on 2024-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_days_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='course',
            name='days_of_week',
            field=models.ManyToManyField(to='main.dayofweek'),
        ),
    ]
