# Generated by Django 5.0.2 on 2024-04-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_course_days_of_week'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayOfWeek',
        ),
    ]
