# Generated by Django 4.2.11 on 2024-04-26 18:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_delete_dayofweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=5)),
                ('name', models.CharField(default='Default Section Name', max_length=50)),
                ('description', models.CharField(default='Default Description', max_length=200)),
                ('start_date', models.DateField(default=django.utils.timezone.now, validators=[main.models.validate_year])),
                ('end_date', models.DateField(default=django.utils.timezone.now, validators=[main.models.validate_year])),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.professor')),
            ],
        ),
    ]
