# Generated by Django 4.2.11 on 2024-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='course_code',
            field=models.CharField(default='Course Code', max_length=4),
        ),
        migrations.AddField(
            model_name='section',
            name='credit',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='section',
            name='grading',
            field=models.CharField(default='Grading Method', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_info',
            field=models.CharField(default='Meeting Information', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='requisites',
            field=models.CharField(default='Requisites Needed', max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='seat_capacity',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.CharField(default='Default Subject', max_length=50),
        ),
        migrations.AddField(
            model_name='section',
            name='topic',
            field=models.CharField(default='Topic', max_length=200),
        ),
    ]
